version: '3.8'

services:
  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    env_file:
      - ./client/.env.production

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - ./server/.env.production
